### ISSUE TITLE
Blender 3.0 version

### ISSUE THREAD

**Issue by art7pro** [Hunanbean/Papagayo-NGLipsyncImporterForBlender#1]
Hello. What about 3.0? When I press _Plot keys to the timeline_ I got this error.

```
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_lipSync_Importer_2_93.py", line 444, in execute
    if scn.fpath!='': lipsyncer()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_lipSync_Importer_2_93.py", line 383, in lipsyncer
    createShapekey(key.name, frame)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_lipSync_Importer_2_93.py", line 412, in createShapekey
    objSK.key_blocks[phoneme].keyframe_insert("value",
TypeError: bpy_struct.keyframe_insert()() takes at most 1 positional argument (4 given)

location: <unknown location>:-1

```

**Comment by Hunanbean** [comment]
This is news to me. I will take a look and see what i see. Thanks for the info

**Comment by Hunanbean** [comment]
I've been looking at this, and it is most likely beyond me. I will continue to try, but i can't make any promises. If you happen to find someone who will fix it for you, please share the update with the rest of us.

**Comment by Hunanbean** [comment]
@art7pro Ok. Luck was with me. I managed to fix the code. Please let me know if you find anything else that does not work.

**Comment by art7pro** [comment]
@Hunanbean Now it works. Thank You Very Much!
